# Generated by Django 3.1.1 on 2020-10-18 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'default_permissions': (), 'managed': False, 'permissions': (('illustrate_player', 'Player Can Illustrate'), ('guess_player', 'Player Can Guess'))},
        ),
    ]
